### ISSUE TITLE
Missing predeploy grant role for CHAIN_CONNECTOR_ROLE

### ISSUE THREAD

**Issue by cstrangedk** [skalenetwork/IMA#1079]
missing in predeploy script
```MessageProxyForSchain.grantRole(CHAIN_CONNECTOR_ROLE, TokenManagerLinker.address)```

┆Issue is synchronized with this [Jira Task](https://skalelabs.atlassian.net/browse/SKALE-5072)

**Comment by payvint** [comment]
Version starting from [1.3.0-develop.2](https://github.com/skalenetwork/IMA/releases/tag/1.3.0-develop.2)

**Comment by DimaStebaev** [comment]
[1.3.1-beta.2](https://github.com/skalenetwork/IMA/releases/tag/1.3.1-beta.2)

**Comment by OleksanderSalamatov** [comment]
Approved to be working on 1.3.5-beta.0 IMA
Case on testrail: C908

`eth.call({to: "0xd2AAa00100000000000000000000000000000000", data: "0x91d148542785f35fe7d8743aa971942d8474737bb31895d396eff2cc688a481e0221e191000000000000000000000000d2aaa00800000000000000000000000000000000"})
"0x0000000000000000000000000000000000000000000000000000000000000001"`
0x0000000000000000000000000000000000000000000000000000000000000001 = True
