### ISSUE TITLE
Move IMA API tests into ethers.js

### ISSUE THREAD

**Issue by sergiy-skalelabs** [skalenetwork/IMA#1081]
Move **IMA API** tests into `ethers.js`. Remove `web3.js` usage completely in all the tests.

┆Issue is synchronized with this [Jira Task](https://skalelabs.atlassian.net/browse/SKALE-5074)

**Comment by Krupalll20** [comment]
heyyy @sergiy-skalelabs can you guide me to contribute on some good first issue
