### ISSUE TITLE
IMA Verify message from mainnet takes more than one min

### ISSUE THREAD

**Issue by EvgeniyZZ** [skalenetwork/IMA#1093]
**Preconditions**

Skaled: 3.14.9-stable.1
IMA: 1.1.3-beta.0

**Step to reproduce**
Run any M2S transfers 

**Expected result**
Verify ima message from mainnet should takes ~30 second(positive case, ima transfer in 100 latest blocks)

**Actual result**
IMA verify takes ~80-90 seconds. As result ima agent can verify 2-3 messages from mainnet(12 transaction deposit
[imaLog.txt](https://github.com/skalenetwork/IMA/files/8442002/imaLog.txt)
[skaledM2S.txt](https://github.com/skalenetwork/IMA/files/8442004/skaledM2S.txt)
)

**Comment by gannakulikova** [comment]
Covered by https://github.com/skalenetwork/ima-agent/issues/22
