### ISSUE TITLE
Invalid argument during M2S ImaVerifyAndSign

### ISSUE THREAD

**Issue by EvgeniyZZ** [skalenetwork/IMA#1138]
**Preconditions**
IMA: 1.3.0-stable.0
Skaled: 3.14.9-stable.5

**Step to reproduce**
Send M2S transfer 
Observe logs

**Actual result**
Invalid argument during ImaVerifyAndSign on part of nodes

NOTE: Issue can be related to SGX ports or proper sgx URL like 192.168.0.1:1026/

**Comment by gannakulikova** [comment]
The root cause is covered by https://github.com/skalenetwork/skaled/issues/1091
