### ISSUE TITLE
wETH transfer in a single transaction

### ISSUE THREAD

**Issue by ebruengwall-ant** [skalenetwork/IMA#1192]
VERY HIGH PRIORITY

wrapped ETH implementation for Ruby to use in S2S so it will be moved to Calypso with a single transaction.  

This should be tested by Engineering and QA:
wETH should be moved in a single transaction
There should be a Security check to make sure the amount is correct. If I send 1000 wETH to Calypso,  If a dApp in Calypso uses 900wETH, the amount returned to Ruby should be only 100 wETH 
wETH should be mapped in two different SKALE chains
wETH should be moved from Schain A to Schain B and vice versa

**Comment by gannakulikova** [comment]
@payvint  to add steps on how to overcome the issue and develop a contract

**Comment by payvint** [comment]
When user transfers _N_ Eth from Mainnet to SKALE-chain - user will receive _N_ tokens of EthERC20 (Eth clone on each SKALE-chain). But EthERC20 can not be used to transfer from SKALE-chain to SKALE-chain. There is [ERC20Wrap](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/extensions/ERC20Wrapper.sol) can be deployed and used for transferring from SKALE-chain to SKALE-chain.

SKALE-chain A owner:
1. Deploy ERC20Wrap with EthERC20 address(`0xD2Aaa00700000000000000000000000000000000`) in constructor.
2. Pass address of ERC20Wrap to SKALE-chain B owner

SKALE-chain B owner:
1. Receive address of ERC20Wrap on SKALE-chain A
2. Deploy ERC20 token which should be a target token
3. Link tokens - addERC20TokenByOwner(SKALE-chain A, address of ERC20Wrap on SKALE-chain A, ERC20 target)

User:
1. Transfer Eth from Mainnet to SKALE-chain A
2. Approve EthERC20 for ERC20Wrap - EthERC20.approve(ERC20Wrap.address, amount)
3. Wrap EthERC20 by executing ERC20Wrap.depositFor(account, amount)
4. Approve ERC20Wrap for TokenManagerERC20- ERC20Wrap.approve(TokenManagerERC20, amount)
4. Transfers ERC20Wrap to SKALE-chain B - transferToSchainERC20(SKALE-chain B, ERC20Wrap.address, amount)

**Comment by payvint** [comment]
@dmitry-tk please take a look on comment above

**Comment by ebruengwall-ant** [comment]
Can you confirm the flow? and also can you double-check the tx amount in the graph if I understand it correctly? 


<img width="803" alt="Screen Shot 2022-07-11 at 12 38 41 PM" src="https://user-images.githubusercontent.com/52053189/178344775-bb10aff1-9225-4d07-9db7-1a00e729774a.png">

**Comment by dmytrotkk** [comment]
I'll prepare a demo with Rinkeby and 2 staging chains
