### ISSUE TITLE
Add `PreviousMessageReference` event

### ISSUE THREAD

**Issue by DimaStebaev** [skalenetwork/IMA#1200]
Add event to support list of messages.

More details in [the documentation](https://github.com/skalenetwork/IMA/blob/ima-search-optimization/docs/ima_linked_list_optimization.md)

**Comment by gannakulikova** [comment]
Need to be verified by QA

**Comment by cstrangedk** [comment]
Already merged, no impact

**Comment by DimaStebaev** [comment]
[1.3.5-beta.0](https://github.com/skalenetwork/IMA/releases/tag/1.3.5-beta.0)

**Comment by DimaStebaev** [comment]
[1.3.1-beta.2](https://github.com/skalenetwork/IMA/releases/tag/1.3.1-beta.2)

**Comment by EvgeniyZZ** [comment]
Verified on [1.3.5-beta.0](https://github.com/skalenetwork/IMA/releases/tag/1.3.5-beta.0)
https://goerli.etherscan.io/tx/0xfc58cddfe7111a4f61d057cae1b9f2faa2bafed7bfc89c05d64383180da31cf5#eventlog
