### ISSUE TITLE
Use `PreviousMessageReference` event for efficient search of new messages

### ISSUE THREAD

**Issue by DimaStebaev** [skalenetwork/IMA#1201]
Use on chain index to search for new messages.

More details in [the documentation](https://github.com/skalenetwork/IMA/blob/ima-search-optimization/docs/ima_linked_list_optimization.md).

**Comment by cstrangedk** [comment]
Note: Agent work for #1200

**Comment by OlgaSkale** [comment]
Need to retest per @EvgeniyZZ

**Comment by DmytroNazarenko** [comment]
IMA: 2.0.0-beta.0

**Comment by EvgeniyZZ** [comment]
Verified: currently for M2S(depends on IMA contract version on chain) transfers will used previousMessageBlockID call during any deposit. In this case agent will know each block where was made transfer. 
https://goerli.etherscan.io/tx/0x06cf649fa3bb75c573d21ad043c66d06c9455ca9692244931356142674a3aa0c#eventloghttps://goerli.etherscan.io/tx/0x06cf649fa3bb75c573d21ad043c66d06c9455ca9692244931356142674a3aa0c#eventlog
2023-08-23 12:14:17.168: M2S/#8985 transfer loop from Mainnet to curly-red-alterf: Will call src-chain->MessageProxy->scan-past-events() for OutgoingMessage event...
2023-08-23 12:14:17.323: M2S/#8985 Will skip progressive scan and use scan in block range from 0x91fb6c to 0x91fb6c

IMA contracts main: 1.3.5-beta.0
IMA agent: 2.0.0-beta.9
