### ISSUE TITLE
Send sFUEL to account after transfer

### ISSUE THREAD

**Issue by cstrangedk** [skalenetwork/IMA#1221]
Accounts need sFUEL onboarding after completing successful transfer between chains.

**Comment by DimaStebaev** [comment]
#1261

**Comment by cstrangedk** [comment]
To prevent incompatibility with certain chains, requires the SKALE Chain owner and/or privileged role to enable/disable.  Default behavior is set as disabled.

**Comment by DimaStebaev** [comment]
[1.3.5-beta.0](https://github.com/skalenetwork/IMA/releases/tag/1.3.5-beta.0)

**Comment by EvgeniyZZ** [comment]
Default value 0 
minRechargeBalanceChanged 
Verified: 
M2S postIncomingMsg
0xc352d16b659f261ae331c967e456ab47d1bfcfa79ba69d4b1c7d872dd8491eae
0x373715add2b1843af35f360aebec2fa774657f2f43d59ff36ebcd1494f7ae98d
