### ISSUE TITLE
Community Pool balance public parameter

### ISSUE THREAD

**Issue by cstrangedk** [skalenetwork/IMA#1235]
`_balanceIsSufficient` is currently a private function.
developers need a public function that can get the balance needed with gasPrice as a parameter.

**Comment by gannakulikova** [comment]
@cstrangedk  can you please advise the release expectations?
Thank you!

**Comment by gannakulikova** [comment]
Assigned to 2.1 release for now

**Comment by payvint** [comment]
Unfortunately we can not make `_balanceIsSufficient` public, `tx.gasprice` would not return a valid "average gasprice" after London fork, it would return 0.

We need to use block.basefee it would return a base fee to last mined block.
To use block.basefee we need to update solidity version, it is not supported in 0.8.6 solidity version.

Test with returning tx.gasprice and block.basefee on Rinkeby and Goerli:

Goerli:
https://goerli.etherscan.io/address/0xa8b21d1009e8ebe8d74e633700f5928a93318e36#readContract

Rinkeby:
https://rinkeby.etherscan.io/address/0x3a552a238cca22c3f895e1f641f5d94c6d528bd9#readContract


Unfortunately hardhat does not support block.basefee in solidity during tests so we can not test properly in unit tests.
https://github.com/NomicFoundation/edr/issues/462

**Comment by payvint** [comment]
Also possible solution:

Have a function which would return how much you need to top up a wallet to be active.
Here I would suggest to use 1.25 or even 1.5 multiplier on a block.basefee to be sure that tx would pass in several next blocks.

**Comment by payvint** [comment]
Based on discussion with Ruby team:

Will add function `getRecommendedRechargeAmount(bytes32 schainHash, address user)` which would return a recommended amount to top up user wallet.
Basefee would be multiplied by 1.5 which can be changed in the future by setting a new multiplier with function `setMultiplier(uint newMultiplierNumerator, uint newMultiplierDivider)`
