### ISSUE TITLE
IMA agent JS only

### ISSUE THREAD

**Issue by sergiy-skalelabs** [skalenetwork/IMA#1248]
Remove `skale_imaVerfyAndSign` and other IMA-related JSON RPC APIs from **skaled** and implement them in **IMA Agent**. Provide **IMA Agent** with all required parameters for BLS-based message signing with **SGX Wallet**.

**Comment by DmytroNazarenko** [comment]
[2.0.0-beta.0](https://github.com/skalenetwork/IMA/releases/tag/2.0.0-beta.0)

**Comment by EvgeniyZZ** [comment]
Not for QA.
