### ISSUE TITLE
ETH event subscription re-check

### ISSUE THREAD

**Issue by sergiy-skalelabs** [skalenetwork/IMA#1253]
We have reports about ETH events are not delivered on subscription but only when web socket (WS) connection is used. HTTP works fine. Ethereum clients like `geth` as well as `skaled` use `eth_subscribe` JSON RPC to start receiving event notifications. This mechanism works different for HTTP and WS. HTTP implementation was inherited in `skaled` from C++ ethereum project. WS implementation was added by SKALE. I.e. we implemented sequential mechanism sending `eth_subscription` notifications from `skaed` server to WS connected client after last invoked `eth_subscribe`. This always worked fine and we have `web3.js` tests for this. But problem is reported for WS connections over `ethers.js`. New `ethers.js` tests are needed and feature must be re-checked.

**Comment by sergiy-skalelabs** [comment]
See full ethers js based test here https://github.com/skalenetwork/SkaleExperimental/tree/master/skaled-tests/test-ethers-contract

**Comment by oleksandrSydorenkoJ** [comment]
Couldn't use https://github.com/skalenetwork/SkaleExperimental/tree/master/skaled-tests/test-ethers-contract - deprecated test
