### ISSUE TITLE
Ability to remap S2S Tokens

### ISSUE THREAD

**Issue by TheGreatAxios** [skalenetwork/IMA#1269]
### Problem
Currently, when a token is mapped over the bridge from one chain to another (S2S) it is immutable. 

### Proposed Solution
There should be a way to remap this token if the value on the target end is 0, as the origin chain does not even need to propose a target address on transfers. 

This means if errors during deployment, the token can be remapped. Once the target has value, this should lock, and once again unlock if balances reach 0 maybe?

**Comment by payvint** [comment]
@TheGreatAxios This is a good idea, we need to add functionality to remove clone if the clone have 0 totalSupply and then you can add it

**Comment by DmytroNazarenko** [comment]
Predeployed only side

**Comment by DmytroNazarenko** [comment]
@badrogger need to update skale-admin with appropriate version of predeployed (ask @yavrsky )

**Comment by DmytroNazarenko** [comment]
skale-admin: 2.6.0-beta.0
ima-predeployed: 2.1.0b0

**Comment by EvgeniyZZ** [comment]
Ima predeployed does not contains new functionality. 
Required version: 2.1.0a1 
TODO: Prepare new version of skale admin that contains required changes @DmytroNazarenko

**Comment by EvgeniyZZ** [comment]
UPD: resolved 
required contracts update OR re-setup schain

**Comment by EvgeniyZZ** [comment]
Version: 2.1.0b0
Logs:
revertReason: "Total supply of a new token is not zero",
NOTE: To get this feature schain owner should update their contract to version 2.1.0b0
