### ISSUE TITLE
Allocate port for IMA Agent JSON RPC server

### ISSUE THREAD

**Issue by sergiy-skalelabs** [skalenetwork/IMA#1289]
**IMA Agent** had to run its own **JSON RPC server** to maintain connection between agents and query them for `1/16` BLS signatures. We need to allocate one port for **JSON RPC server** in **IMA Agent** same as we do for **skaled**.

**Comment by gannakulikova** [comment]
Review: to be reassigned to 2.2?

**Comment by sergiy-skalelabs** [comment]
yes, 2.2

**Comment by DmytroNazarenko** [comment]
[2.0.0-beta.0](https://github.com/skalenetwork/IMA/releases/tag/2.0.0-beta.0)

**Comment by EvgeniyZZ** [comment]
Verified: Allocated separate port base +10
IMA Agent: 2.0.0-beta.7
