### ISSUE TITLE
Move IMA Agent synchronization out of skaled

### ISSUE THREAD

**Issue by sergiy-skalelabs** [skalenetwork/IMA#1312]
The `skale_imaTxnInsert`, `skale_imaTxnErase`, `skale_imaTxnClear`, `skale_imaTxnFind` and `skale_imaTxnListAll` JSON RPC APIs are currently implemented as part of `skaled` and used to detect whether previous IMA Agent(s) exceeded execution of its(their) time frame(s) and still running an unfinished job. These JSON RPC APIs should be moved from `skaled` into `IMA Agent` because last one now running its own JSON RPC server.

**Comment by DmytroNazarenko** [comment]
Close as duplicate
