### ISSUE TITLE
Move ALL-SKALE/functional test into public repo

### ISSUE THREAD

**Issue by sergiy-skalelabs** [skalenetwork/IMA#1320]
`ALL-SKALE/functional test` is part of private repo and it teats time on github actions. We need to move it into public repo

**Comment by DmytroNazarenko** [comment]
Do this files contain any sensitive data:

https://github.com/skalenetwork/functional-test/blob/master/.github/workflows/main.yml#L406
https://github.com/skalenetwork/functional-test/blob/master/functional_check/cli-ganache/run.sh
https://github.com/skalenetwork/functional-test/blob/master/functional_check/cli-hh/hardhat.config.js
https://github.com/skalenetwork/functional-test/blob/master/functional_check/engine/.env
https://github.com/skalenetwork/functional-test/blob/master/functional_check/s_chain_gen/g_arrEcdsaKeysCache.json
https://github.com/skalenetwork/functional-test/blob/master/functional_check/s_chain_gen/cfg.js
https://github.com/skalenetwork/functional-test/blob/master/functional_check/test_tokens/truffle-config.js
https://github.com/skalenetwork/functional-test/blob/master/functional_check/test_tokens/hardhat.config.js

**Comment by sergiy-skalelabs** [comment]
@DmytroNazarenko @gannakulikova These files contain only test private keys we use in many JS tests. Nothing sensitive.

**Comment by DmytroNazarenko** [comment]
Good, no problem. How about migrating this repo to the new one (public, with clear history)

**Comment by gannakulikova** [comment]
completed
