### ISSUE TITLE
Fix random build failure

### ISSUE THREAD

**Issue by cstrangedk** [skalenetwork/IMA#1341]
see https://github.com/skalenetwork/IMA/actions/runs/3534055444/jobs/5930476823#step:16:520

**Comment by payvint** [comment]
Looks like bytes32 string became bytes31 string:)
```
1) ERC721MintingFromSchainToMainnet
[518](https://github.com/skalenetwork/IMA/actions/runs/3534055444/jobs/5930476823#step:16:519)
       "before each" hook for "should not send message if not registered":
[519](https://github.com/skalenetwork/IMA/actions/runs/3534055444/jobs/5930476823#step:16:520)
     Error: incorrect data length (argument=null, value="0xbdecb447c02cb45c912ea72dc3ea66fb9c8a3339b9df544cc512f07089fb27", code=INVALID_ARGUMENT, version=abi/5.4.1)
```

`len("0xbdecb447c02cb45c912ea72dc3ea66fb9c8a3339b9df544cc512f07089fb27") = 64 = 2 + 2 * 31`

**Comment by payvint** [comment]
My assumption:
In this test there is only one place where some rand string is used [here](https://github.com/skalenetwork/IMA/blob/develop/proxy/test/extensions/ERC721MintingFromSchainToMainnet.ts#L131) 
After that we extract public key from private key [here](https://github.com/skalenetwork/IMA/blob/develop/proxy/test/extensions/ERC721MintingFromSchainToMainnet.ts#L163)

Review [getPublicKey function](https://github.com/skalenetwork/IMA/blob/develop/proxy/test/utils/helper.ts#L69) - it uses function hexlify over getX().toBuffer() function - hexlify can return non fixed to 32 bytes and getX is returning number and converting to bytes array also it is non fixed to 32 bytes.
So I think it would be good to rewrite this function and use already created solutions from ethers or web3 libraries.
