### ISSUE TITLE
Ima msg counter erased to 0 on schain part

### ISSUE THREAD

**Issue by DmytroNazarenko** [skalenetwork/IMA#1403]
**Description**
By unknown reason state on ima contract was changed. 

**What we know**
On part of nodes IncomingMessagesCounter become 0 
We can't clarify when it happen because: 
- logs are missing 
- skaled not supported calls with specific blocknumber 
State root miss match becomes before sending messages to IMA. 
We have different sate on schain 11 and 5 
See counter field, nodes where 0 are corrupted

!Logs are absent
Logs: [testData.txt](https://github.com/skalenetwork/internal-support/files/8634741/testData.txt)

Original issue: https://github.com/skalenetwork/internal-support/issues/96

**Comment by PolinaKiporenko** [comment]
need to retest

**Comment by DmytroNazarenko** [comment]
[2.0.0-beta.0](https://github.com/skalenetwork/IMA/releases/tag/2.0.0-beta.0)

**Comment by EvgeniyZZ** [comment]
Can't reproduce. 
Can be related to catchup from 0 block with different pereployed version. 
IMA: 3.17.0-beta.7
