### ISSUE TITLE
IMA frames stop work after some time

### ISSUE THREAD

**Issue by DmytroNazarenko** [skalenetwork/IMA#1407]
Preconditions:
IMA: 1.1.3-beta.0
Skaled: 3.14.9-stable.1

Description:
After some time in ima agent frames stop working on part of agents

Step to reproduce:
Not have have exec steps right now

Actual result:
After some time ima frames(loop) stop working, as result ima transfers not working properly.

Note: container up and running, our health check not catch this problem. Need to clarify root cause.

**Comment by sergiy-skalelabs** [comment]
See PR here https://github.com/skalenetwork/IMA/pull/1452

**Comment by DmytroNazarenko** [comment]
[2.0.0-beta.0](https://github.com/skalenetwork/IMA/releases/tag/2.0.0-beta.0)
