### ISSUE TITLE
Improve IMA integration tests

### ISSUE THREAD

**Issue by sergiy-skalelabs** [skalenetwork/IMA#1453]
IMA integration tests are running on each pull request and cover most of Solidity and JavaScript code. Unfortunatelly not all the code and much more functions can be covered. We need add more small per-function and per-feature tests.

**Comment by DmytroNazarenko** [comment]
[2.0.0-beta.0](https://github.com/skalenetwork/IMA/releases/tag/2.0.0-beta.0)

**Comment by EvgeniyZZ** [comment]
Not for QA
