### ISSUE TITLE
Refactor source code of IMA Agent to follow Code Guidelines

### ISSUE THREAD

**Issue by sergiy-skalelabs** [skalenetwork/IMA#1478]
Refactor source code of **IMA Agent** to follow **Code Guidelines** https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md

**Comment by sergiy-skalelabs** [comment]
Working branches are `ticket-737/IMA-switch-toethers-js-v1.6.0` and `ticket-737/IMA-switch-toethers-js`.

**Comment by sergiy-skalelabs** [comment]
PR is https://github.com/skalenetwork/IMA/pull/1452

**Comment by DmytroNazarenko** [comment]
[2.0.0-beta.0](https://github.com/skalenetwork/IMA/releases/tag/2.0.0-beta.0)
