### ISSUE TITLE
Separate logs for different log levels

### ISSUE THREAD

**Issue by EvgeniyZZ** [skalenetwork/IMA#1481]
We should have at lease two log levels like *info* and *debug*. 
Info - should used in regular work 
Debug - during troubleshooting problems 

List of information what should be moved to debug level. 

- [ ] Full response from SNB requests
- [ ] BLS Glue information
- [ ] Information of collecting signatures

Note: additional points may be added later during final review

**Comment by DmytroNazarenko** [comment]
[2.0.0-beta.0](https://github.com/skalenetwork/IMA/releases/tag/2.0.0-beta.0)
