### ISSUE TITLE
Minor bug: remove trash zeros in logs

### ISSUE THREAD

**Issue by sergiy-skalelabs** [skalenetwork/IMA#1493]
Latest `IMA 2.0.0 beta 0` has minor issue in colorized log output - un-needed redundant one `0`-zero characters in the beginning of log lines starting with high resolution time-stamp value. These `0`-zero characters must be removed in `log.js` file:
```
export function createStandardOutputStream() {
... ... ...
            "write": function( s ) {
                const x =
                    this.strOwnIndent +
                    ( this.haveOwnTimestamps ? generateTimestampPrefix( null, true ) : "" ) +
                    s;
                try {
                    if( this.objStream )
                        this.objStream.write( x );
                } catch ( err ) { }
            },
... ... ...

```
Here is screen shot demonstrating the problem:
![Screenshot from 2023-06-20 15-51-42](https://github.com/skalenetwork/IMA/assets/44965319/d3cc7943-e90e-4adb-b916-a716f14e43db)

**Comment by DmytroNazarenko** [comment]
IMA: [2.0.0-beta.3](https://github.com/skalenetwork/IMA/releases/tag/2.0.0-beta.3)

**Comment by EvgeniyZZ** [comment]
Unclear description. Mark as resolved/can't reproduce.
