### ISSUE TITLE
Fix monitoring subsystem logging issue on new connection

### ISSUE THREAD

**Issue by sergiy-skalelabs** [skalenetwork/IMA#1512]
We have tiny non critical issue in logging code of **IMA Agent**'s monitoring subsystem. An `undefined` value is printed into log instead of network/origin address of connected JSON RPC client. Here is the message in log:
```
2023-06-26 16:04:04.360: Job 1: 0 task(s) failed
2023-06-26 16:04:04.361: Job 1: ===================================================
Initialized in-worker IMA loop ima_loop_server0 server
2023-06-26 16:04:26.515: Monitoring: New connection from undefined
```
Last line above shows the problem.

**Comment by DmytroNazarenko** [comment]
IMA: [2.0.0-beta.3](https://github.com/skalenetwork/IMA/releases/tag/2.0.0-beta.3)

**Comment by EvgeniyZZ** [comment]
Verified: Can't reproduce. 
IMA Agent: 2.0.0-beta.12
