### ISSUE TITLE
IMA Agent automatic restart was not removed 

### ISSUE THREAD

**Issue by EvgeniyZZ** [skalenetwork/IMA#1514]
**Description**
Automatic restart was added as temporary solution to resolve unexpected stuck of IMA Agent. 

**Preconditions** 
Schain created
IMA Agent version: 2.0.0-beta.2

 
**Steps To Reproduce**
Update IAM Agent to 2.0.0-beta.2 version 
Observe agent init log

**Actual result**
2023-06-27 12:11:46.981: Automatic exit after 3600 second(s) is requested.
2023-06-27 13:11:49.055: Automatic exit after 3600 second(s) is requested.

**Expected behavior**
IMA Agent should not restarted at all.

**Comment by DmytroNazarenko** [comment]
IMA: [2.0.0-beta.3](https://github.com/skalenetwork/IMA/releases/tag/2.0.0-beta.3)

**Comment by EvgeniyZZ** [comment]
Verified:  Automatic exit after  was removed
IMA Agent: 3.17.0-beta.7
