### ISSUE TITLE
IMA Agent frame stuck in case of unsuccessful re-discover

### ISSUE THREAD

**Issue by EvgeniyZZ** [skalenetwork/IMA#1515]
**Preconditions**
Schain created
IMA Agent: 2.0.0-beta.0

**Step to reproduce**
Turn off one node of schain(RPC down )
Update another node to 2.0.0-beta.0 version

**Actual result**
IMA frame stuck 

Logs: [imaRediscover.txt](https://github.com/skalenetwork/IMA/files/11884981/imaRediscover.txt)
```[tasklist]
### Tasks
- [ ] https://github.com/skalenetwork/IMA/issues/1584
```

**Comment by EvgeniyZZ** [comment]
We need to fix it asap. 
Required for update procedure

**Comment by DmytroNazarenko** [comment]
IMA: [2.0.0-beta.3](https://github.com/skalenetwork/IMA/releases/tag/2.0.0-beta.3)

**Comment by EvgeniyZZ** [comment]
Verified: Agent not stuck during re-discover or initialization. 
IMA Agent: ima:2.0.0-beta.13

2023-09-19 18:45:28.164: S-Chain network discovery: Have S-Chain description response about 13 of 16 node(s).
2023-09-19 18:45:28.164: S-Chain network discovery: This S-Chain discovery will finish with 13 of 16 node(s) discovered.
Related issue:  added as sub task
