### ISSUE TITLE
Fix docker script of IMA Agent

### ISSUE THREAD

**Issue by sergiy-skalelabs** [skalenetwork/IMA#1520]
Docker script of **IMA Agent**, known as `agent/run.sh` does not require `RPC_PORT` environment variable to be always specified and does not pass it value to command line of **IMA Agent** as `--json-rpc-$RPC_PORT` parameter. This must be fixed ASAP.
Additionally, the `agent/run.sh` script does not allow to specify all the possible command line keys **IMA Agent** does support. This limits testing capabilities of docker image and based on it containers.

**Comment by DmytroNazarenko** [comment]
IMA: [2.0.0-beta.3](https://github.com/skalenetwork/IMA/releases/tag/2.0.0-beta.3)

**Comment by EvgeniyZZ** [comment]
Verified: base rpc port N+10 only 
IMA Agent: 2.0.0-beta.7
