### ISSUE TITLE
Fix missing v support in joinSignature of ethers.js

### ISSUE THREAD

**Issue by sergiy-skalelabs** [skalenetwork/IMA#1530]
**IMA Agent** uses `r` + `s` parts of **ECDSA Signrature** coming from **SGX Wallet**. We had to compute `v` part manually and invoke `ethers.utils.joinSignature` to get final binary signature used in transaction submitting. It turns out, `ethers.utils.joinSignature` is partially implmented and now allow to use custom `v` values corresponding to custom `chainId`:
```
function joinSignature(signature) {
    signature = splitSignature(signature);
    return hexlify(concat([
        signature.r,
        signature.s,
        (signature.recoveryParam ? "0x1c" : "0x1b")
    ]));
}

```
Instead it's force using standard `27`/`28` values corresponding to `-4`. We need to write manual signature joining code.

Blocks:
- S2S transfers
- M2S transfers

**Comment by sergiy-skalelabs** [comment]
**Ethers JS v 6** has even worst code where you can see `v` exmplicitly required to be `27` or `28`:
```
    set v(value: BigNumberish) {
        const v = getNumber(value, "value");
        assertArgument(v === 27 || v === 28, "invalid v", "v", value);
        this.#v = v;
    }
```

**Comment by sergiy-skalelabs** [comment]
`ethersWallet.sendTransaction` also ignores `chainId` specified for it inside `ethersProvider` and generates signatures with `v=1`.

**Comment by DmytroNazarenko** [comment]
@sergiy-skalelabs 
1. to try QA sgx and check whether the problem is in sgx setup
2. to try https://github.com/skalenetwork/sgx.py/blob/b9dddabf4dd5972c0eaddd66bdb333d84b66bb22/sgx/sgx.py#L237 in IMA

**Comment by EvgeniyZZ** [comment]
Not for QA
