### ISSUE TITLE
Fix communication issues between agent loop, SNB and main worker threads in IMA agent.

### ISSUE THREAD

**Issue by sergiy-skalelabs** [skalenetwork/IMA#1547]
Problem reproduce-able on dev-net only. Communication between agent loop, SNB and main worker threads is broken. At least SNB messages are not broadcasted between these threads. As result, workers do not know array of S-Chains connected to this S-Chain and S2S transfers does not occur.

**Comment by EvgeniyZZ** [comment]
Verified: Can't reproduce particular case. 
IMA Agent: 2.0.0-beta.9
