### ISSUE TITLE
Radically improve log writing API inside IMA Agent

### ISSUE THREAD

**Issue by sergiy-skalelabs** [skalenetwork/IMA#1550]
Idea is to remove logging verbisity check conditions like `if( log.verboseGet() >= log.verboseReversed().debug )` before each `log.write()` and `details.write()` invocations. We need to move verbosity check into `log.write()`.
We need to use code like `log.write( value, value ...)` instead of `log.write( cc...(value), cc...(value) ...)`. I.e. remove `cc.something()` optional colorization, remove `cc.j(...)` JSON formatting and do everything inside only after log verbosity tells it to really print out.
This is relatively big task be becase of too many logging likes in source code of each JS file of IMA Agent.

**Comment by PolinaKiporenko** [comment]
ima-agent: 2.1.0-beta.2
