### ISSUE TITLE
Estimate gas failed during using POW 

### ISSUE THREAD

**Issue by EvgeniyZZ** [skalenetwork/IMA#1553]
**Description**
In some cases(most common - node rotation) node can have 0 balance of SFuel. 
In this case should be used POW algorithm. 

**Environment**
IMA Agent: 2.0.0-beta.7
Network: [Regression](https://github.com/skalenetwork/internal-support/blob/main/docs/testing-space/test-environments/network-Regression/Regression.md)
Schain name: portly-passionate-sirius

**Step to reproduce**
- Run node rotation tests OR make node SFuel balance to 0. 
- Run any IMA transfer(S2M, S2S)
- Observe logs 

**Actual result**
IMA message verified and failed on tx processing. 

**Expected behavior**
Estimate gas works properly during POW and tx processing 

[imaInsufficientSF.txt](https://github.com/skalenetwork/IMA/files/12336455/imaInsufficientSF.txt)

**Comment by EvgeniyZZ** [comment]
Verified: Not working. Now its not working when balance is more 0.
IMA Agent: 2.0.0-beta.9


[imaPowStillNotWorking.txt](https://github.com/skalenetwork/IMA/files/12422269/imaPowStillNotWorking.txt)
[imaPowStillNotWorkingPOW.txt](https://github.com/skalenetwork/IMA/files/12422285/imaPowStillNotWorkingPOW.txt)

**Comment by DmytroNazarenko** [comment]
IMA:  2.0.0-beta.10

**Comment by EvgeniyZZ** [comment]
Verified: estimateGas wokrs during POW.
IMA Agent: 
Node address balance: 0 
PoW-mining is needed for sender 0x5ad0ffdb09bd8cc90ff73e489e7caa47e2483601 with balance 0x00 using required balance 0x01162d1d711400
[powWorkNow.txt](https://github.com/skalenetwork/IMA/files/12664730/powWorkNow.txt)
