### ISSUE TITLE
IMA transfer loop work unstable 

### ISSUE THREAD

**Issue by EvgeniyZZ** [skalenetwork/IMA#1566]
**Description**
IMA M2S loop work unstable before/after S2M transfers. 
UPD: All transfer loop have same problem 

**Environment**
IMA Agent: 2.0.0-beta.9
Network: [Regression](https://github.com/skalenetwork/internal-support/blob/main/docs/testing-space/test-environments/network-Regression/Regression.md)
Schain name: curly-red-alterf

**Step to reproduce** 
- Make S2M transfer
- Make M2S transfer 
- Observe IMA agent log 
OR
- Make M2S transfer 
- Observe IMA agent log 

**Actual result**
IMA M2S transfer loop stuck/or not started. No error msg in logs of IMA agent. 
In a while M2S loop start work again. 

**Expected behavior**
IMA M2S transfer loop work stable. Agent request outgoingMsgConunter each 10-15 seconds

*NOTE*
Geth node work properly, not geth issue!

Logs:
https://goerli.etherscan.io/tx/0x06cf649fa3bb75c573d21ad043c66d06c9455ca9692244931356142674a3aa0c
https://goerli.etherscan.io/tx/0x517e84d8012a4226facf5c6e35b491c72355d74c85d907f3a7b01fcccbdf1c2f
Compare timestamps on mainnet and processing time start on schain 
[imaM2STransferStuck.txt](https://github.com/skalenetwork/IMA/files/12420268/imaM2STransferStuck.txt)

**Comment by DmytroNazarenko** [comment]
IMA: 2.0.0-beta.10
