### ISSUE TITLE
Move IMA agent to a separate repo

### ISSUE THREAD

**Issue by DmytroNazarenko** [skalenetwork/IMA#1577]
Current repo structure holds in one repo:
- IMA mainnet contracts
- IMA predeployed contracts
- IMA agent

To make IMA to have more modular structure we need to retrieve IMA agent into separate repo and set up the separate versioning system for it

**Comment by PolinaKiporenko** [comment]
ima: 2.1.0-beta.2
ima-agent: 2.1.0-beta.2
ima-predeployed:  2.1.0b0
