### ISSUE TITLE
IMA Agent not refresh data in cache after init

### ISSUE THREAD

**Issue by EvgeniyZZ** [skalenetwork/IMA#1584]
**Description**
Transfer type: unrelated 
Network: Regression 
Components: 
IMA: 2.0.0-beta.9(or any)
At least 2(A,B)  schain on the network 

**Steps to reproduce**
Connect schains to each other  
Observe logs(i.e transfer loop s2s)

**Actual result**
Currently IMA Agent make discover network only after initialization 

**Expected result**
IMA Agent should refresh data before start work.

Required action: 
- discuss the frequency of data updates
- add logs for this action(i.e: {timestamp}{action start}{action end+result})

**Comment by EvgeniyZZ** [comment]
Verified: cache still not updating on schain from time to time. 
IMA Agent: 2.0.0-beta.12

Note: Assume that ``Connected S-Chains cache was updated`` - main thread

**Comment by DmytroNazarenko** [comment]
IMA: 2.0.0-beta.16

**Comment by EvgeniyZZ** [comment]
Verified: Reopen. In case if first attempt of SNB was unsuccessful cache will not updated at all. 
Logs below describe behavior of different chains on the same node.
IMA Agent: 2.0.0-beta.16


[imaRefreshCache.txt](https://github.com/skalenetwork/IMA/files/12717899/imaRefreshCache.txt)

**Comment by EvgeniyZZ** [comment]
Verified: Agent worked  several days without any time/preference gaps 
IMA Agent: 2.0.0-beta.17
