### ISSUE TITLE
Fix BLS signatures gathering stuck

### ISSUE THREAD

**Issue by sergiy-skalelabs** [skalenetwork/IMA#1595]
Fix the following problems
- BLS signatures gathered with delays one by one, node by node. They must gather parallel and independent.
- If one node is down, then rest of BLS signatures are gathered with huge delay.

**Comment by EvgeniyZZ** [comment]
Can't reproduce: signature gathering going in parallel 
IMA Agent version: 2.0.1


[blsAwait.txt](https://github.com/skalenetwork/IMA/files/13417465/blsAwait.txt)
