### ISSUE TITLE
SNB does not invoked with default time interval 1 hour

### ISSUE THREAD

**Issue by sergiy-skalelabs** [skalenetwork/IMA#1602]
SNB uses default time interval 1 hour to refresh list of S-Chains currently connected to this S-Chain. This periodic refresh does not happen because of `setInterval` JS API does not work well with long time intervals like 1 hour. And this is often discussed in various JS discussion forums. We need to fix behavior of this timer based work.

**Comment by EvgeniyZZ** [comment]
Verified: marked as resolved. 
Related to: https://github.com/skalenetwork/internal-support/issues/868
Version: 2.0.1
